export const OPEN_FOLDER = 'OPEN_FOLDER';
export const OPEN_FOLDER_SUCCESS = 'OPEN_FOLDER_SUCCESS';
export const OPEN_FOLDER_ERROR = 'OPEN_FOLDER_ERROR';
export const CLOSE_FOLDER = 'CLOSE_FOLDER';
export const CLOSE_FOLDER_SUCCESS = 'CLOSE_FOLDER_SUCCESS';
export const CLOSE_FOLDER_ERROR = 'CLOSE_FOLDER_ERROR';